sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

services:
  - docker

before_install:
  - docker pull skarupa/cpp-env
  - docker run -id --name RedCam --mount type=bind,src=/home/travis/build/AdharaOrigin/workflow,dst=/app skarupa/cpp-env
  - docker ps

# Build steps
script:
  - docker exec -it RedCam /bin/bash -c "cd /app && cmake . && make"
